package com.aho.streambrowser.util

import com.aho.streambrowser.model.NetworkRequest
import com.aho.streambrowser.model.StreamItem
import com.aho.streambrowser.model.StreamQuality
import com.aho.streambrowser.model.StreamType

object CurlExporter {
    
    /**
     * Convert NetworkRequest to cURL command
     */
    fun toCurl(req: NetworkRequest): String {
        return buildString {
            appendLine("# cURL command")
            appendLine("# URL: ${req.url}")
            appendLine("# Method: ${req.method}")
            if (req.host.isNotEmpty()) {
                appendLine("# Host: ${req.host}")
            }
            appendLine()
            append("curl -X ${req.method} ")
            
            // Add headers
            req.headers.forEach { (key, value) ->
                val escapedValue = value.replace("'", "'\\''")
                append("-H '$key: $escapedValue' ")
            }
            
            // Add Referer if present
            if (req.referer.isNotEmpty()) {
                append("-H 'Referer: ${req.referer}' ")
            }
            
            // Add User-Agent if not present
            if (!req.headers.containsKey("User-Agent")) {
                append("-H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36' ")
            }
            
            append("'${req.url}'")
            
            // Add response info as comments
            if (req.statusCode > 0) {
                appendLine()
                appendLine()
                appendLine("# Response: ${req.statusCode}")
                if (req.mimeType.isNotEmpty()) {
                    appendLine("# Content-Type: ${req.mimeType}")
                }
                if (req.contentLength > 0) {
                    appendLine("# Content-Length: ${req.contentLength}")
                }
            }
        }
    }
    
    /**
     * Convert StreamItem to M3U8 playlist format
     */
    fun toM3U8(stream: StreamItem): String {
        return buildString {
            appendLine("#EXTM3U")
            appendLine("#EXT-X-VERSION:3")
            
            when (stream.type) {
                StreamType.HLS -> {
                    appendLine("#EXTINF:-1,${stream.displayName}")
                    appendLine(stream.url)
                }
                StreamType.MP4 -> {
                    appendLine("#EXTINF:-1,${stream.displayName}")
                    appendLine(stream.url)
                }
                StreamType.DASH -> {
                    appendLine("# DASH Manifest")
                    appendLine("# MPD URL: ${stream.url}")
                }
                StreamType.FLV -> {
                    appendLine("# FLV Stream")
                    appendLine(stream.url)
                }
                else -> {
                    appendLine("# Stream URL: ${stream.url}")
                }
            }
            
            appendLine()
            appendLine("#EXT-X-ENDLIST")
        }
    }
    
    /**
     * Export multiple streams as batch M3U8 playlist
     */
    fun toBatchM3U8(streams: List<StreamItem>): String {
        return buildString {
            appendLine("#EXTM3U")
            appendLine("# Generated by Stream Browser")
            appendLine("# Total streams: ${streams.size}")
            appendLine()
            
            streams.forEachIndexed { index, stream ->
                appendLine("# Stream ${index + 1}")
                appendLine("# Type: ${stream.type}")
                appendLine("# Quality: ${stream.qualityLabel}")
                appendLine("# Codec: ${stream.codec ?: "Unknown"}")
                appendLine("#EXTINF:-1,${stream.displayName}")
                appendLine(stream.url)
                appendLine()
            }
            
            appendLine("#EXT-X-ENDLIST")
        }
    }
}

object CloudStreamExporter {
    
    /**
     * Convert StreamItem to CloudStream ExtractorLink format
     */
    fun toExtractorLink(stream: StreamItem): String {
        val isM3u8 = stream.type == StreamType.HLS || stream.type == StreamType.DASH
        val quality = when (stream.quality) {
            StreamQuality.P1080 -> "Qualities.P1080"
            StreamQuality.P720 -> "Qualities.P720"
            StreamQuality.P480 -> "Qualities.P480"
            StreamQuality.P360 -> "Qualities.P360"
            StreamQuality.P240 -> "Qualities.P240"
            StreamQuality.P1440 -> "Qualities.P1440"
            StreamQuality.P4K -> "Qualities.P2160"
            StreamQuality.UNKNOWN -> "Qualities.Unknown"
        }
        
        return """
callback(
    ExtractorLink(
        source   = "Custom",
        name     = "${stream.displayName}",
        url      = "${stream.url}",
        referer  = "${stream.referer}",
        quality  = ${quality}.value,
        isM3u8   = ${isM3u8},
        headers  = mapOf(
            "Referer"    to "${stream.referer}",
            "User-Agent" to "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        )
    )
)""".trimIndent()
    }
    
    /**
     * Export multiple streams as batch ExtractorLinks
     */
    fun toBatchExtractorLinks(streams: List<StreamItem>): String {
        return buildString {
            streams.forEachIndexed { index, stream ->
                if (index > 0) appendLine()
                appendLine("// Stream ${index + 1}: ${stream.displayName}")
                append(toExtractorLink(stream))
            }
        }
    }
}
