package com.aho.streambrowser.util

import com.aho.streambrowser.model.NetworkRequest
import com.aho.streambrowser.model.StreamItem
import com.aho.streambrowser.model.StreamType

/** I1: Generate CloudStream3 plugin skeleton from captured session */
object PluginGenerator {

    data class SessionData(
        val streams:   List<StreamItem>,
        val requests:  List<NetworkRequest>,
        val siteUrl:   String,
        val cookies:   String,
        val referer:   String
    )

    /** Generate full extractorLink code from captured streams */
    fun generateExtractorCode(session: SessionData): String {
        val sb = StringBuilder()
        sb.appendLine("// Auto-generated by StreamBrowser v3")
        sb.appendLine("// Site: ${session.siteUrl}")
        sb.appendLine("// Captured: ${session.streams.size} stream(s)")
        sb.appendLine()
        sb.appendLine("override suspend fun loadLinks(")
        sb.appendLine("    data: String, isCasting: Boolean,")
        sb.appendLine("    subtitleCallback: (SubtitleFile) -> Unit,")
        sb.appendLine("    callback: (ExtractorLink) -> Unit")
        sb.appendLine("): Boolean {")
        if (session.streams.isEmpty()) {
            sb.appendLine("    // No streams captured — implement manually")
            sb.appendLine("    return false")
        } else {
            session.streams.take(3).forEachIndexed { i, stream ->
                val type = if (stream.type == StreamType.HLS) "ExtractorLinkType.M3U8" else "ExtractorLinkType.VIDEO"
                sb.appendLine()
                sb.appendLine("    // Stream ${i + 1} [${stream.source}]")
                sb.appendLine("    callback(newExtractorLink(")
                sb.appendLine("        source = name,")
                sb.appendLine("        name   = name,")
                sb.appendLine("        url    = \"${stream.url}\",")
                sb.appendLine("        type   = $type")
                sb.appendLine("    ) {")
                sb.appendLine("        quality = Qualities.P1080.value")
                sb.appendLine("        headers = mapOf(")
                sb.appendLine("            \"User-Agent\" to \"Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36\",")
                sb.appendLine("            \"Referer\"    to \"${session.referer}\"" +
                    if (session.cookies.isNotBlank()) "," else "")
                if (session.cookies.isNotBlank())
                    sb.appendLine("            \"Cookie\"     to \"${session.cookies.take(200)}\"")
                sb.appendLine("        )")
                sb.appendLine("    })")
            }
            sb.appendLine()
            sb.appendLine("    return true")
        }
        sb.appendLine("}")
        return sb.toString()
    }

    /** Generate full plugin skeleton */
    fun generateSkeleton(pluginName: String, siteUrl: String): String {
        val clean = pluginName.replace(Regex("[^A-Za-z0-9]"), "")
        return """
package com.lagradost.cloudstream3.plugins

import com.lagradost.cloudstream3.*
import com.lagradost.cloudstream3.plugins.*
import com.lagradost.cloudstream3.utils.*
import com.lagradost.cloudstream3.network.CloudflareKiller

@CloudstreamPlugin
class ${clean}Plugin : Plugin() {
    override fun load() { registerMainAPI(${clean}Provider()) }
}

class ${clean}Provider : MainAPI() {
    override var mainUrl        = "$siteUrl"
    override var name           = "$clean"
    override val hasMainPage    = true
    override var lang           = "vi"
    override val supportedTypes = setOf(TvType.Anime, TvType.Movie)

    private val cfKiller = CloudflareKiller()

    override suspend fun getMainPage(page: Int, request: MainPageRequest): HomePageResponse {
        // TODO: implement browse/pagination
        return newHomePageResponse(request.name, emptyList())
    }

    override suspend fun search(query: String): List<SearchResponse> {
        // TODO: implement search
        return emptyList()
    }

    override suspend fun load(url: String): LoadResponse {
        // TODO: parse episode detail page
        throw ErrorLoadingException("Not implemented")
    }

    override suspend fun loadLinks(
        data: String, isCasting: Boolean,
        subtitleCallback: (SubtitleFile) -> Unit,
        callback: (ExtractorLink) -> Unit
    ): Boolean {
        // TODO: extract stream URL
        return false
    }
}
""".trimIndent()
    }

    /** Reverse-engineer URL pattern from captured requests */
    fun analyzePatterns(requests: List<NetworkRequest>): String {
        val sb = StringBuilder("// URL Patterns found:\n")
        val apiCalls = requests.filter { r ->
            r.url.contains("api") || r.url.contains("json") || r.url.contains("data")
        }.take(10)
        apiCalls.forEach { r ->
            sb.appendLine("// ${r.method} ${r.url.take(100)}")
            if (r.headers.isNotEmpty()) {
                r.headers.filter { (k, _) -> k.lowercase() !in listOf("host", "connection", "accept-encoding") }
                    .forEach { (k, v) -> sb.appendLine("//   $k: ${v.take(60)}") }
            }
        }
        val streamReqs = requests.filter { it.isStream }.take(5)
        if (streamReqs.isNotEmpty()) {
            sb.appendLine("\n// Stream requests:")
            streamReqs.forEach { r -> sb.appendLine("// ${r.url.take(100)}") }
        }
        return sb.toString()
    }
}
